@startuml

class Post {
  +name: String
}

class FinancialAidForm {
  +applicantName: String
  +applicantReason: String
}

class NoticeBoard {
  +posts: Post[*]
}

class Warning {
  +status: String
  +active: Boolean
}

class Graduation {
  +graduationMonth: Integer
}

class Job {
  +startingDate: Integer
}

class Student {
  +name: String
  +section: String
  +rollNumber: Integer
  +CNIC: Integer
  +batch: Integer
  +CGPA: Real
  +indigent: Boolean
  +approvalAcquired: Boolean
  +warningCount: Integer
  +currentDegreeDuration: Integer
  +feeDefaulterApproved: Boolean
  +realNeedOfAssistance: Boolean
  +loan: Loan[?]
  +scholarship: Scholarship[?]
  +degree: DegreeProgram[1]
  +transcript: Transcript[1]
  +warnings: Warning[*|1]
  +job: Job[?]
  +graduation: Graduation[?]
}

class DegreeProgram {
  +name: String
  +type: Type
  +warningCount: Integer
  +minCGPA: Real
  +maxTime: Integer
  +onWarning: Boolean
  +coreCourses: Course[*]
  +electiveCourses: Course[*]
}

class Transcript {
  +semesters: Semester[*|1]
  +displayedCourses: Course[*|1]
}

class Semester {
  +name: String
  +year: Integer
  +SGPA: Real
  +CGPA: Real
  +creditAttended: Integer
  +creditEarned: Integer
  +withdrawalDeadline: Date
  +finished: Boolean
  +startingInNumWeeks: Integer
  +enrolledCourses: Course[*|1]
  +offeredCourses: Course[*|1]
  +fee: Fee[1]
}

class Department {
  +name: String
  +HOD: String
  +offeredCourses: Course[*|1]
}

class Marks {
  +quizMarks: Real
  +assignmentMarks: Real
  +midMarks: Real
  +finalMarks: Real
  +projectMarks: Real
}

class Date {
  +year: Integer
  +month: Integer
  +day: Integer
}

class Course {
  +courseName: String
  +courseCode: String
  +creditHours: Integer
  +repeatCount: Integer
  +currentDate: Date
  +announcedDate: Date
  +registrationDate: Date
  +canAppearInExam: Boolean
  +grade: Grade
  +status: CourseStatus
  +importance: CourseImportance
  +resultsAnnounced: Boolean
  +retakeApproved: Boolean
  +attendance: Attendance[1]
  +semester: Semester[1]
  +studiedBy: Student[*]
  +marks: Marks[1]
}

class Attendance {
  +numLectures: Integer
  +attendancePercentage: Real
}

class University {
  +name: String
  +ranking: Integer
}

class Campus {
  +location: String
  +meritList: MeritList[1]
  +studentList: Student[*|1]
  +departmentList: Department[*|1]
}

class MeritList {
  +positionHolders: PositionHolder[*|1]
}

class PositionHolder {
  +paper: Paper
}

class Loan {
  +eligible: Real
  +renewalCriteriaMet: Boolean
  +assistanceType: String
  +repaymentStartMonth: Integer
  +repaymentEndMonths: Integer
  +renewedEverySemester: Boolean
}

class Scholarship {
  +offered: Boolean
  +awarded: Boolean
  +coverage: Real
  +numSems: Integer
}

class Fee {
  +amount: Integer
  +refund: Boolean
  +paid: Boolean
  +paymentMethod: String
  +dueInWeeks: Integer
  +type: FeeType
}

class Type {
  +MS
  +BS
}

Post <|-- FinancialAidForm
Post <|-- NoticeBoard
Warning -- Student
Graduation -- Student
Job -- Student
DegreeProgram "1" -- "1..*" Course
Student "1" -- "0..*" Loan
Student "1" -- "0..*" Scholarship
Student "1" -- "1" DegreeProgram
Student "1" -- "1" Transcript
Student "0..*" -- "0..1" Warning
Student "0..*" -- "0..1" Job
Student "0..*" -- "0..1" Graduation
DegreeProgram "*" -- "0..*" Course
Semester "*" -- "0..*" Course
Semester "1" -- "1" Fee
Course "1" -- "0..*" Student
Course "1" -- "1" Semester
Course "1" -- "1" Attendance
Campus "1" -- "1" MeritList
MeritList "1" -- "0..*" PositionHolder
PositionHolder <|-- Student
Loan "0..1" -- "1" Student
Scholarship "0..1" -- "1" Student
Fee "1" -- "1" Semester

@enduml
